# Generated by Django 4.2.9 on 2024-07-20 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('title', 'release_date'),
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=70, null=True, verbose_name='Улица')),
                ('house', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('type', models.CharField(choices=[('factory', 'factory'), ('retail', 'retail'), ('seller', 'seller')], default='factory', max_length=7, verbose_name='Тип продавца')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность перед поставщиком')),
                ('products', models.ManyToManyField(blank=True, to='network.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.networknode', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Звено',
                'verbose_name_plural': 'Звенья',
                'ordering': ('title', 'type'),
            },
        ),
    ]
