# Generated by Django 4.2.9 on 2024-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='type',
            field=models.CharField(choices=[('factory', 'завод'), ('retail', 'розничная сеть'), ('seller', 'индивидуальный предприниматель')], default='factory', max_length=7, verbose_name='Тип продавца'),
        ),
    ]
